version: '3.9'

services:
  web:
    build: .
    container_name: gen_ai
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1